#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --allow-unsafe --generate-hashes '.\requirements_dev.txt'
#



# Automated checks related
pip-tools==5.3.1 \
    --hash=sha256:5672c2b6ca0f1fd803f3b45568c2cf7fadf135b4971e7d665232b2075544c0ef \
    --hash=sha256:73787e23269bf8a9230f376c351297b9037ed0d32ab0f9bef4a187d976acc054
    # via -r .\requirements_dev.txt
pre-commit==2.9.3 \
    --hash=sha256:6c86d977d00ddc8a60d68eec19f51ef212d9462937acf3ea37c7adec32284ac0 \
    --hash=sha256:ee784c11953e6d8badb97d19bc46b997a3a9eded849881ec587accd8608d74a4
    # via -r .\requirements_dev.txt
pylint-django==2.4.2 \
    --hash=sha256:355dddb25ef07dbdb77a818b0860ada722aab654c24da34aab916ec26d6390ba \
    --hash=sha256:f8d77f7da47a7019cda5cb669c214f03033208f9e945094661299d2637c0da06
    # via -r .\requirements_dev.txt
black==20.8b1 \
    --hash=sha256:1c02557aa099101b9d21496f8a914e9ed2222ef70336404eeeac8edba836fbea
    # via -r .\requirements_dev.txt
# The following packages are considered to be unsafe in a requirements file:
setuptools==50.3.0 \
    --hash=sha256:39060a59d91cf5cf403fa3bacbb52df4205a8c3585e0b9ba4b30e0e19d4c4b18 \
    --hash=sha256:c77b3920663a435c9450d9d971c48f5a7478fca8881b2cd2564e59f970f03536
    # via
    #   -r .\requirements_dev.txt
    #   google-api-core
    #   google-auth
    #   gunicorn
    #   ipdb
    #   ipython
    #   protobuf

pip==20.3.3 \
    --hash=sha256:79c1ac8a9dccbec8752761cb5a2df833224263ca661477a2a9ed03ddf4e0e3ba \
    --hash=sha256:fab098c8a1758295dd9f57413c199f23571e8fde6cc39c22c78c961b4ac6286d
    # via
    #   -r .\requirements_dev.txt
    #   pip-tools

